### ISSUE TITLE
Fix the CSS in about page.

### ISSUE THREAD

**Issue by BIIJESH** [b0sc/b0sc.github.io#18]
- [X] PR for this issue must follow the PR template
- [ ] This is a bug
- [ ] This is a feature request

## For Bug 
- What happened?
- What should have happened?
## For Feature request 
- Explain the working of new feature.
- How will implementing this help this repo?
- Relevant examples and resources
![image](https://github.com/user-attachments/assets/846753d0-980e-4548-aa6c-55b71f65a332)

**Comment by raijin-asr** [comment]
I am bit confused. Current website of BOSC has team member section in two columns as given below but this issue description has four columns image attached. So should anyone transform 2 columns team members to 4 columns or not?

![4 cloumn Team member ss0 before](https://github.com/user-attachments/assets/c2d2c654-657b-4415-bd87-c24c521fa18c)

**Comment by raijin-asr** [comment]
Q. If task is to make 4 column team members with CSS fixed. then which of the following is suitable?

1.  just image shape uniform..
![4 cloumn Team member ss1](https://github.com/user-attachments/assets/e68a627b-8502-4863-8157-08aeab730e9a)


2. since existing green style photo has unique shape,,,leave or make other image as it is.
![4 column Team member ss3](https://github.com/user-attachments/assets/7376048f-ea36-4dd4-a882-6edd68b6b1bf)


3. or all photo in circle shape
![4 column Team member ss2](https://github.com/user-attachments/assets/de55953b-e2bb-4000-a481-aa257c363b02)

**Comment by axyut** [comment]
@BIIJESH

**Comment by axyut** [comment]
@raijin-asr keep the circle photo layout for everyone, with fixed height/width(should be responsive) other than this i think its already pretty responsive and lets close this issue. also the reason youre only getting 2 columns in desktop mode might be because your display is zoomed in or the aspect ratio of your monitor is low. I can see four coulmns in my monitor even at 125% zoom but it goes to 2 columns once i hit 133% zoom. so develop in maybe 100% zoom for you or even less.
